name: CI
on: push

# Explicit permissions required for GITHUB_TOKEN to push the deployment
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Swapped out broken token for built-in auth
          submodules: recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.32"

      - name: Build
        # remove --minify tag if you do not need it (ahg: I removed it - was "run: hugo --minify")
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Swapped out here too for smooth deployment
          # external_repository: wordbit/wordbit/tree/master/public (ahg: commenting out because I'm not using external repo)
          publish_dir: ./public
          #   keep_files: true
          user_name: wordbit
          user_email: wordbit@gmail.com
          publish_branch: gh-pages
          cname: wordbit.com
